# 端到端自动化流水线配置文件
# 默认值仅供参考，可根据实际情况修改

# 拍照阶段配置
capture:
  camera_id: 0                 # 相机ID，对于OpenCV通常为0，对于工业相机可能是序列号
  use_industry_cam: false      # 是否使用工业相机，如果为true则尝试使用PyCapture2等SDK

# 提示生成阶段配置
prompt:
  hand_gesture: "握住"          # 默认手势描述
  # 可以为特定物体配置特殊手势
  object_gestures:
    cracker_box: "展示"
    sugar_box: "拿着"

# Sora视频生成阶段配置
sora:
  # Chrome浏览器配置
  chrome_user_dir: null        # Chrome用户数据目录路径，如果为null则使用系统默认位置
                               # Windows通常为: C:\Users\用户名\AppData\Local\Google\Chrome\User Data
                               # macOS通常为: ~/Library/Application Support/Google/Chrome
  max_attempts: 3              # 最大尝试次数
  poll_interval: 10            # 轮询间隔（秒）
  use_mock: false              # 是否使用模拟模式（不调用真实API）
  headless: false              # 是否使用无头模式运行浏览器

# 规则过滤阶段配置
rule_filter:
  enabled: true                # 是否启用规则过滤
  flow_threshold: 1.5          # 光流阈值，越小要求相机越静止
  detection_threshold: 0.5     # 检测阈值
  min_frame_ratio: 0.8         # 最小帧比例，要求至少80%的帧满足条件
  sample_interval: 5           # 采样间隔，每隔多少帧检查一次
  # 特定物体的阈值设置
  object_thresholds:
    cracker_box:
      flow_threshold: 2.0
      min_frame_ratio: 0.7

# 模型过滤阶段配置（可选）
model_filter:
  enabled: false               # 是否启用模型过滤
  model_path: null             # 模型路径，如果为null则使用未训练的模型（不推荐）
  threshold: 0.7               # 阈值，高于此值视为通过
  # 特定物体的阈值设置
  object_thresholds:
    cracker_box: 0.6
    sugar_box: 0.75

# 视频转PNG阶段配置
video2png:
  use_ffmpeg: true             # 是否使用FFmpeg，否则使用OpenCV
  quality: 2                   # 输出质量（1-31，越小质量越高）

# 流水线整体配置
pipeline:
  auto_retry: 3                # 自动重试次数
  early_stop_on_failure: true  # 是否在阶段失败时提前停止
  failed_dir: "failed"         # 失败样本保存目录 